"""m2m table3

Revision ID: 918fea6f286f
Revises: 78609a0def31
Create Date: 2024-05-29 13:45:01.194599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918fea6f286f'
down_revision: Union[str, None] = '78609a0def31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('seeds_collection_id_fkey', 'seeds', type_='foreignkey')
    op.drop_column('seeds', 'collection_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('seeds_collection_id_fkey', 'seeds', 'seeds_collection', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
